### ISSUE TITLE
Invite other members to BEP032

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/.github#6]
I do not have super powers to manage users of the organization. So here is the list of people which need to be added to the People of the bids-specification organization and then to the https://github.com/orgs/bids-standard/teams/bep032 team:

NB edited to include some from the comments below:

- @bendichter
- @oruebel
- @ree-gupta
- @twachtler 
- @dyf

**Comment by twachtler** [comment]
@twachtler
@ree-gupta

**Comment by yarikoptic** [comment]
ok, I was given god's privileges, and invited everyone!  please visit https://github.com/bids-standard and agree to join the team ;)
